---
- name: Déploiement des Load Balancers HA (Keepalived + HAProxy)
  hosts: loadbalancers
  become: true
  roles:
    - keepalived
    - haproxy

- name: Déploiement du cluster K3s
  hosts: k3s_servers
  become: true
  roles:
    - k3s

- name: Deploy Proxmox Monitoring Infrastructure
  hosts: monitoring
  become: yes
  roles:
    - monitoring